version: "3.9"
networks: 
  calculajurosNet:

services:

  calculajuros:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: calculajuros
    networks: 
      - calculajurosNet
    ports: 
      - 8002:80
  